# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

  
[[main]]
  name = "Material"
  identifier = "mat"
  weight = 10
  
[[main]]
  name = "Handouts"
  parent = "mat"
  weight = 10
  url = "#handout"
  
[[main]]
  name = "Extra"
  parent = "mat"
  weight = 20
  url = "extra/"
  
[[main]]
  name = "Worksheet and Data"
  identifier = "wsd"
  weight = 20
  
[[main]]
  name = "Session 1"
  weight = 10
  parent = "wsd"
  url = "assets/session1.zip"
  
[[main]]
  name = "Session 2"
  weight = 20
  parent = "wsd"
  url = "assets/session2.zip"

[[main]]
  name = "Session 3"
  weight = 30
  parent = "wsd"
  url = "assets/session3.zip"
  
[[main]]
  name = "Session 4"
  weight = 40
  parent = "wsd"
  url = "assets/session4.zip"
  
[[main]]
  name = "Session 5"
  weight = 50
  parent = "wsd"
  url = "assets/session5.zip"
  
[[main]]
  name = "Session 6"
  weight = 60
  parent = "wsd"
  url = "assets/session6.zip"
  
[[main]]
  name = "Session 7"
  weight = 70
  parent = "wsd"
  url = "assets/session7.zip"
  
[[main]]
  name = "Slide Deck"
  weight = 40
  identifier = "slides"
  
[[main]]
  name = "Session 1: Welcome"
  parent = "slides"
  weight = 10
  url = "slides/session_1/session_1_welcome.html"
  
[[main]]
  name = "Session 2: dplyr"
  parent = "slides"
  weight = 20
  url = "slides/session_2/session_2_EDA_summary.html"
  
[[main]]
  name = "Session 6: Functions and Data Types"
  parent = "slides"
  weight = 20
  url = "slides/session_6/function_and_data_types.html"
  
# [[main]]
# name = "Full Publications"
# url = "publication/"
# weight = 20


#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10
#
#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30
#
#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40
#
#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50
#
#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60
#
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
